### ISSUE TITLE
Only shows the parent navigation

### ISSUE THREAD

**Issue by jshenderson** [tom-daly/sp2013-bootstrap-nav#1]
I am testing your navigation script (love how easy it was to implement). When I publish it though it ignores the current site's navigation and grabs the navigation of the parent. 

Should I change the queryUrl variable to ensure i get the current site?

**Comment by tom-daly** [comment]
Thank you for the feedback. I haven't tested it just yet but you should be able to have it read from the current site navigation by changing line 13 

from:
config.siteUrl = _spPageContextInfo.siteAbsoluteUrl;

to: 
config.siteUrl = _spPageContextInfo.webAbsoluteUrl;

**Comment by jshenderson** [comment]
FIRST-- thank you for responding.

Second, UM YES! It works!! 
I actually tried that earlier, but I was verifying that it was in fact pulling the parent no matter what, and had all the navigation off. :|

One more question, is this script supposed to add the "home" link to the top nav? It currently doesn't show anything unless I explicitly tell it to. So when there is nothing under Global not even the home link. 

Is there way to add that?

**Comment by tom-daly** [comment]
It adds only what is returned from this call. Basically only what you have defined and no home node unless you specify it. 

{YOURSITE}/_api/navigation/menustate?mapprovidername=%27GlobalNavigationSwitchableProvider%27

you could just always add a home node. after line 59.. before the $.each statement you could put pop this in there. 

`nodeGroup.append("<li><a href='http://www.thomasdaly.net'>Home</a></li>");`

or if you want that home node to be the site url you could use 

`nodeGroup.append("<li><a href='" + _spPageContextInfo.siteAbsoluteUrl + "'>Home</a></li>");`

**Comment by jshenderson** [comment]
Tom,
Thank you. This is great. Also, it's refreshing to ask a question and not be talked down to in order to get an answer. I appreciate you helping us make SharePoint better for our users and for being a good teacher.
