### ISSUE TITLE
2nd level not showing

### ISSUE THREAD

**Issue by jshenderson** [tom-daly/sp2013-bootstrap-nav#2]
If i add a link under a header in the navigation. It stops appending nav links at the parent of the drop down.
So it will completely render the navigation, even the parent of the drop down, and show the caret, but it does not append the child link, or any link after.

**Comment by tom-daly** [comment]
Thank you again! I see the issue. The navigation nodes 'Key' value is set to a link and the jQuery can't find the parent.

I just corrected the issue. Now I'm generating my own unique key for each node and using that to link back to the parents.

please pull down the latest script. v0.3 I just checked it in now.

**Comment by jshenderson** [comment]
Perfect. Thank you.
