### ISSUE TITLE
Simple Link or Header  vs Term Driven Page

### ISSUE THREAD

**Issue by pjatdy** [tom-daly/sp2013-bootstrap-nav#3]
Hi Tom,  If a term is designated as a "Simple Link or Header" with an empty URL, it should become a plain text header with no link.  I noticed that if a term is set up as such, and your script is used, it is still assigned a link rather than becoming a plain text item.  Can this be addressed?  If this does not make sense, please let me know.

This is working great otherwise.  Thanks again!

**Comment by tom-daly** [comment]
thanks for the feedback. I think that this can be addressed. I'm away for the weekend but will take a look at making this possible sunday/monday

**Comment by tom-daly** [comment]
looking at this today - sorry for the delay.
