### ISSUE TITLE
Website will only show the parent navigation 

### ISSUE THREAD

**Issue by StefanBreedveld** [tom-daly/sp2013-bootstrap-nav#4]
I have also parent navigation problem.
Just as in the issue from 'jshenderson' it ignores the current site's navigation and grabs the navigation of the parent. This happens because I have set the setting 'useCache' to 'true'. If I set it to 'false' then the navigation is showed correctly for the site / subsite.

I have set the 'useCache' to 'true' because only then my smooth scrolling jScript works fine for navigating on a one page website.

**Comment by tom-daly** [comment]
i'm looking into this

**Comment by tom-daly** [comment]
right, just thought about this. so useCache stores the first pull of the nav into the browser. If you go to a subsite and useCache is true it won't even bother to make the call to retrieve the nav again.  In this case you would not want to set useCache to true.

**Comment by tom-daly** [comment]
if your navigation changes from site to site then use cache in it's current instance won't buy you savings. I would have to write in some functionality to check navigation on reload and if the same ignore and if different refresh. There would be a potential flash of the old navigation so I'm not sure I want to go that route now.

**Comment by StefanBreedveld** [comment]
Ok thanks for your time. If there is no easy solution than don't bother. Our out-of-the box topnavigation works fine but yours is (especially for mobile) much better!
